// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    { type: "doc", label: "Rencontre 1.1", id: "cours/accueil" },
    { type: "doc", label: "Rencontre 1.2", id: "cours/accueil" },
    { type: "doc", label: "Rencontre 1.3", id: "cours/rencontre1.2" }
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
};

module.exports = sidebars;
