// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    { type: "doc", label: "Rencontre 1.1", id: "cours/accueil" },
    { type: "doc", label: "Rencontre 1.2", id: "cours/accueil" },
    { type: "doc", label: "Rencontre 2.1", id: "cours/imperatif" },
    { type: "doc", label: "Rencontre 2.2", id: "cours/imperatif" },
    { type: "doc", label: "Rencontre 3.1", id: "cours/imperatif" },
    { type: "doc", label: "Rencontre 3.2", id: "cours/integration-1" },
    { type: "doc", label: "Rencontre 4.1", id: "cours/std-lib" },
    { type: "doc", label: "Rencontre 4.2", id: "cours/std-lib" },
    { type: "doc", label: "Rencontre 5.1", id: "cours/librairies" },
    { type: "doc", label: "Rencontre 5.2", id: "cours/exceptions" },
    { type: "doc", label: "Rencontre 6.1", id: "cours/formatif-intra" },
    { type: "doc", label: "Rencontre 6.2", id: "cours/examen" },
    { type: "doc", label: "Rencontre 7.1", id: "cours/intro-android" },
    { type: "doc", label: "Rencontre 7.2", id: "cours/activites" },
    { type: "doc", label: "Rencontre 8.1", id: "cours/menu" },
    { type: "doc", label: "Rencontre 8.2", id: "cours/recycler" },
    { type: "doc", label: "Rencontre 9.1", id: "cours/recycler" },
    { type: "doc", label: "Rencontre 9.2", id: "cours/recycler" },
    { type: "doc", label: "Rencontre 10.1", id: "cours/integration-2" },
    { type: "doc", label: "Rencontre 10.2", id: "cours/room" },
    { type: "doc", label: "Rencontre 11.1", id: "cours/room" },
    { type: "doc", label: "Rencontre 11.2", id: "cours/room" },
    { type: "doc", label: "Rencontre 12.1", id: "cours/service" },
    { type: "doc", label: "Rencontre 12.2", id: "cours/tests" },
    { type: "doc", label: "Rencontre 13.1", id: "cours/tests" },
    { type: "doc", label: "Rencontre 13.2", id: "cours/tests" },
    { type: "doc", label: "Rencontre 14.1", id: "cours/librairies-android" },
    { type: "doc", label: "Rencontre 14.2", id: "cours/integration-3" },
    { type: "doc", label: "Rencontre 15.1", id: "cours/formatif-final" },
    { type: "doc", label: "Rencontre 15.2", id: "cours/examen" },
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
};

module.exports = sidebars;
