// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    { type: "doc", label: "Rencontre 1.1", id: "cours/accueil" },
    { type: "doc", label: "Rencontre 1.2", id: "cours/accueil" },
    { type: "doc", label: "Rencontre 2.1", id: "cours/imperatif" },
    { type: "doc", label: "Rencontre 2.2", id: "cours/imperatif" },
    { type: "doc", label: "Rencontre 3.1", id: "cours/imperatif" },
    { type: "doc", label: "Rencontre 3.2", id: "cours/integration-1" },
    { type: "doc", label: "Rencontre 4.1", id: "cours/std-lib" },
    { type: "doc", label: "Rencontre 4.2", id: "cours/std-lib" },
    { type: "doc", label: "Rencontre 5.1", id: "cours/librairies" },
    { type: "doc", label: "Rencontre 5.2", id: "cours/exceptions" },
    { type: "doc", label: "Rencontre 6.1", id: "cours/formatif-intra" },
    { type: "doc", label: "Rencontre 6.2", id: "cours/examen" },
    { type: "doc", label: "Rencontre 7.1", id: "cours/intro-android" },
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
};

module.exports = sidebars;
